#!/usr/bin/env bash
# Bash script that pings an IP address passed as an argument.

if[$# -eq 0]; then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	exit
fi

IP_ADDRESS=$1

ping -c 5 $IP_ADDRESS | while read line; do
	if [[ $line == *"time="* ]]; then
		time=$(echo $line | grep -oP '(?<=time=)[0-9.]+')
        	echo "Round-trip time: $time ms"
	if
	echo "$line"
done

