#!/usr/bin/env bash
# bash script that Creates the file /var/run/myscript.pid containing its PID

cleanup() {
    echo "Cleaning up and exiting..."
    rm -f /var/run/myscript.pid
    exit 0
}

trap 'cleanup' SIGQUIT SIGTERM

# Trap interrupt signal and display message
trap 'echo "Y U no love me?!"' SIGINT
echo $$ > /var/run/myscript.pid

while true; do
    echo "To infinity and beyond"
    sleep 1
done
