#!/usr/bin/env bash
# script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r username _ uid gid info home shell
do
    group=$(grep -E "^.*?:[^:]*:$gid:" /etc/group | cut -d ':' -f1)

    password=$(grep -E "^$username:" /etc/shadow | cut -d ':' -f2)

    echo "The user $username is part of the $group gang, lives in $home and rides $shell."
    echo "User ID $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
