#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:display hours from 0 to 12,display minutes from 1 to 59

for ((hours=0; hours<=12; hours++))
do
    for ((minutes=1; minutes<=59; minutes++))
    do
        echo "$hours:$minutes"
    done
done
