#!/usr/bin/env bash
# script that displays the time for 12 hours and 59 minutes:display hours from 0 to 12,display minutes from 1 to 59

hours=0
minutes=1

while [ "$hours" -le 12 ]
do
    echo "$hours:$minutes"
    ((minutes++))

    if [ "$minutes" -eq 60 ]; then
        ((hours++))
        minutes=1
    fi
done | head -n 70
