#!/usr/bin/env bash
#script that displays:The content of the current directory In a list format 
for file in *
do
    if [[ ! "$file" == .* && "$file" == *-* ]]
    then
        name=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name"
    fi
done
