#!/usr/bin/env bash
#Bash script that configures an Ubuntu server with the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
#The checker is running on Docker, so make sure to read this

if [ -f "/.dockerenv" ]; then
    echo "Configuring hosts file..."
    echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null
    echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
    echo "Hosts file configured successfully."
else
    echo "This script is intended to run on Docker. Exiting."
    exit 1
fi
