#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

ipv4_addresses=$(ifconfig | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
filtered_addresses=$(echo "$ipv4_addresses" | grep -vE "^127\.")
echo "Active IPv4 addresses:"
echo "$filtered_addresses"
